// Copyright The Mumble Developers. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file at the root of the
// Mumble source tree or at <https://www.mumble.info/LICENSE>.

#ifndef MUMBLE_MUMBLE_INPUTENHANCEMENTCALIBRATION_H_
#define MUMBLE_MUMBLE_INPUTENHANCEMENTCALIBRATION_H_

#include "InputEnhancement.h"

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <span>

namespace Mumble::InputEnhancement {

/// Owns the privacy- and safety-critical state for one input-enhancement
/// calibration. The session deliberately does no file, network or settings
/// I/O. A controller may persist resultSelection() only after apply().
///
/// All PCM storage is allocated before start(). appendPcm(), advance(),
/// candidate recording and terminal transitions are allocation-free and do
/// not acquire locks. The captured PCM is securely overwritten on every
/// terminal path and again in the destructor.
class CalibrationSession final {
public:
	static constexpr unsigned int sampleRate         = 48'000;
	static constexpr unsigned int levelCheckSeconds  = 1;
	static constexpr unsigned int roomNoiseSeconds   = 8;
	static constexpr unsigned int guidedVoiceSeconds = 12;
	static constexpr unsigned int localNoiseSeconds  = 8;

	static constexpr std::size_t levelCheckSamples      = sampleRate * levelCheckSeconds;
	static constexpr std::size_t roomNoiseSamples       = sampleRate * roomNoiseSeconds;
	static constexpr std::size_t guidedVoiceSamples     = sampleRate * guidedVoiceSeconds;
	static constexpr std::size_t localNoiseSamples      = sampleRate * localNoiseSeconds;
	static constexpr std::size_t requiredStorageSamples = roomNoiseSamples + guidedVoiceSamples + localNoiseSamples;
	static constexpr std::size_t maximumCandidates      = 8;

	enum class State : std::uint8_t {
		Idle,
		LevelCheck,
		LevelCheckReady,
		RoomNoise,
		RoomNoiseReady,
		GuidedVoice,
		GuidedVoiceReady,
		LocalNoise,
		LocalNoiseReady,
		Evaluating,
		BlindComparison,
		DraftReady,
		Applied,
		Cancelled,
		Aborted,
		Error
	};

	enum class LevelStatus : std::uint8_t { Collecting, Good, TooQuiet, Clipping };

	enum class FailureReason : std::uint8_t {
		None,
		InvalidStorage,
		InvalidPcm,
		InvalidCandidate,
		CandidateCapacityExceeded,
		EvaluationFailed,
		AbortedByCaller
	};

	struct Selection final {
		Profile profile           = Profile::Original;
		int noiseReduction        = 50;
		int naturalCrisp          = 50;
		std::uint32_t recipeToken = 0;

		bool operator==(const Selection &) const = default;
	};

	struct LevelMetrics final {
		float peak          = 0.0f;
		float rms           = 0.0f;
		std::size_t samples = 0;
		LevelStatus status  = LevelStatus::Collecting;
	};

	/// Non-owning views valid only until the next state-machine call. They are
	/// exposed solely for synchronous local recipe + Opus evaluation.
	struct CaptureView final {
		std::span< const float > roomNoise;
		std::span< const float > guidedVoice;
		std::span< const float > localNoise;
	};

	struct CandidateResult final {
		Selection selection;
		double objectiveScore              = 0.0;
		bool eligible                      = true;
		bool localPipelineAndOpusEvaluated = false;
		bool loudnessMatched               = false;
	};

	/// Tokens are opaque UI playback handles. They intentionally do not expose
	/// which recipe is on the left or right side of the blind comparison.
	struct BlindPair final {
		std::uint64_t leftPlaybackToken  = 0;
		std::uint64_t rightPlaybackToken = 0;
	};

	/// Allocates the fixed 28-second PCM arena. This happens outside the audio
	/// thread; all subsequent PCM ingestion is allocation-free.
	CalibrationSession();

	/// Uses caller-owned, already allocated PCM storage. The storage must remain
	/// alive until destruction and is securely cleared by this object. This
	/// constructor is noexcept so allocation-sensitive owners can reserve their
	/// arena ahead of time.
	explicit CalibrationSession(std::span< float > preallocatedStorage) noexcept;
	~CalibrationSession();

	CalibrationSession(const CalibrationSession &)            = delete;
	CalibrationSession(CalibrationSession &&)                 = delete;
	CalibrationSession &operator=(const CalibrationSession &) = delete;
	CalibrationSession &operator=(CalibrationSession &&)      = delete;

	/// Starts a new local-only calibration. blindSeed should be generated by the
	/// controller for each session; supplying a fixed seed makes tests and
	/// qualification runs deterministic.
	bool start(const Selection &previousSelection, bool captureOptionalLocalNoise, std::uint64_t blindSeed) noexcept;

	/// Consumes at most the remaining samples for the current capture step.
	/// Callers must observe the Ready state and advance() before submitting the
	/// next prompted step, preventing audio from leaking across prompt borders.
	std::size_t appendPcm(std::span< const float > samples) noexcept;

	/// Advances a completed step. A failed level check is recoverable: this
	/// returns false and restarts the level check without retaining its PCM.
	bool advance() noexcept;
	bool skipOptionalLocalNoise() noexcept;

	CaptureView captureView() const noexcept;
	bool recordCandidate(const CandidateResult &candidate) noexcept;
	bool finishEvaluation() noexcept;
	/// Lets the local evaluator terminate safely when model/Opus processing
	/// fails. This restores the prior selection and wipes captured PCM.
	bool failEvaluation() noexcept;
	BlindPair blindPair() const noexcept;

	/// Intended for the local playback backend, not for presentation in the UI.
	/// The UI should retain only the opaque token and left/right label.
	const Selection *selectionForPlaybackToken(std::uint64_t playbackToken) const noexcept;
	bool selectBlindWinner(std::uint64_t playbackToken) noexcept;

	/// Apply returns the blind winner; Cancel/Abort/Error restore the prior
	/// selection. Every terminal transition clears raw PCM before returning.
	bool apply() noexcept;
	bool cancel() noexcept;
	bool abort() noexcept;

	State state() const noexcept;
	FailureReason failureReason() const noexcept;
	LevelMetrics levelMetrics() const noexcept;
	const Selection *draftSelection() const noexcept;
	const Selection *resultSelection() const noexcept;

	/// Voice transmission is forbidden for the complete active session, not
	/// only while appendPcm() is executing.
	bool transmissionAllowed() const noexcept;

	/// Invariant probe useful to qualification tests and privacy diagnostics.
	/// It reports only whether the arena is zero; it never exposes captured PCM.
	bool rawAudioCleared() const noexcept;

private:
	struct CandidateSlot final {
		CandidateResult result;
	};

	void initializeStorage(float *storage, std::size_t storageSamples) noexcept;
	bool active() const noexcept;
	bool selectionValid(const Selection &selection) const noexcept;
	std::size_t appendLevelCheck(std::span< const float > samples) noexcept;
	std::size_t appendRaw(std::span< const float > samples, std::size_t offset, std::size_t targetSamples,
						  std::size_t &capturedSamples, State readyState) noexcept;
	void resetLevelCheck() noexcept;
	void enterEvaluation() noexcept;
	void fail(FailureReason reason) noexcept;
	void clearRawAudio() noexcept;
	static std::uint64_t mixToken(std::uint64_t value) noexcept;

	std::unique_ptr< float[] > m_ownedStorage;
	float *m_storage             = nullptr;
	std::size_t m_storageSamples = 0;
	bool m_storageValid          = false;

	State m_state                 = State::Idle;
	FailureReason m_failureReason = FailureReason::None;
	Selection m_previousSelection;
	Selection m_draftSelection;
	Selection m_resultSelection;
	bool m_hasDraft                  = false;
	bool m_hasResult                 = false;
	bool m_captureOptionalLocalNoise = false;
	std::uint64_t m_blindSeed        = 0;

	LevelMetrics m_levelMetrics;
	double m_levelSquareSum          = 0.0;
	std::size_t m_roomCaptured       = 0;
	std::size_t m_voiceCaptured      = 0;
	std::size_t m_localNoiseCaptured = 0;

	std::array< CandidateSlot, maximumCandidates > m_candidates = {};
	std::size_t m_candidateCount                                = 0;
	std::size_t m_leftCandidate                                 = 0;
	std::size_t m_rightCandidate                                = 0;
	BlindPair m_blindPair;
};

} // namespace Mumble::InputEnhancement

#endif // MUMBLE_MUMBLE_INPUTENHANCEMENTCALIBRATION_H_
