name: CodeQL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_OPTIONS: |
      -Dtests=OFF -Dsymbols=ON -Dwarnings-as-errors=OFF -Dtest-lto=OFF

jobs:
  pre_run:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
          skip_after_successful_duplicate: 'true'

  CodeQL-Build:
    needs: pre_run
    if: needs.pre_run.outputs.should_skip != 'true'

    runs-on: ubuntu-24.04

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
          fetch-depth: 1

    - name: Initialize submodules with retry
      shell: bash
      run: bash "$GITHUB_WORKSPACE/.github/workflows/update_submodules_with_retry.sh"

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
          languages: python, cpp

    - name: Set environment variables
      run: $GITHUB_WORKSPACE/.github/workflows/set_environment_variables.sh "ubuntu-24.04" "static" "x86_64" "${{ github.workspace }}"
      shell: bash

    - name: Select Linux build components
      shell: bash
      run: |
          echo "MUMBLE_BUILD_CLIENT=OFF" >> "$GITHUB_ENV"
          echo "MUMBLE_BUILD_SERVER=ON" >> "$GITHUB_ENV"

    - uses: ./.github/actions/install-dependencies
      with:
          type: static
          os: ubuntu-24.04
          arch: x86_64

    - name: Build Linux server for CodeQL
      run: ./.github/workflows/build.sh "ubuntu-24.04" "static" "x86_64"
      shell: bash
      env:
          MUMBLE_BUILD_NUMBER: 0

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
